services:
  api:
    build: .
    ports:
      - "8088:8088"
  redis:
    image: "redis:alpine"
  memcached:
    image: memcached
  mongo:
    image: "mongo"
    labels:
      go: test
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongoDBdata:/data/db
  mongo-express:
    depends_on:
     - mongo
    image: "mongo-express"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  data: {}
  mongoDBdata: {}